### ISSUE TITLE
Suggestion: YAML & args

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-cli#40]
If I understood, I can either use args or a YAML but I can't do both.
I'd love this behaviour to change, here's my point of view: 

I intend to have many YAML prepared for different use cases. Here's one 

```yaml
transaction_type: contract
content: |
  hello
  world
smart_contract: |
  @version 1
  condition inherit: [ content: true ]
  actions triggered_by: interval, at: "* * * * *" do 
    Contract.set_content Time.now()
  end
```

In the YAML I do not care about which network nor which keychain is sending the transaction. That's why I'd like to separate the `data` from the `keychain & network`. 

I could then do `./archethic-cli send-transaction --seed XXX --index 0 --endpoint local --config contract.yaml` . 
What do you think?
